name: CI/CD Pipeline

on:
  push:
    branches:
      - newversion  # Replace 'main' with your preferred branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add your build and deployment steps here
    # For example, you can run tests, build your application, or deploy to a hosting service.
    # You can use different actions or scripts based on your project's requirements.
    - name: Copying files from submodule
      run: |
          git submodule update --init --recursive
          cd /home/runner/work/azure-arc-webapp-new/azure-arc-webapp-new/azure-arc-docs
          ls
          cp -r /home/runner/work/azure-arc-webapp-new/azure-arc-webapp-new/azure-arc-docs/docs/* /home/runner/work/azure-arc-webapp-new/azure-arc-webapp-new/azure-arc-jumpstart-app/public/docs
          git add .
          git commit -m "updates"
          git push
